spring:
  datasource:
    url: jdbc:mysql://localhost/person?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

  flyway:
    locations: classpath:db/migration,classpath:db/testdata

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false
