ALTER TABLE person
    MODIFY first_name VARCHAR(100) NOT NULL,
    MODIFY last_name VARCHAR(100) NOT NULL,
    MODIFY address VARCHAR(100) NOT NULL,
    MODIFY gender VARCHAR(50) NOT NULL,
    MODIFY email VARCHAR(100) NOT NULL;
